POST https://discord.com/api/v8/channels/790890428567257088/messages
Content-Type: application/json
Authorization: Bot NzYxNTkwMTM5MTQ3MTI0ODEw.X3c0Fg.iCXl-m52KcN_XVxXjI4CC1F0P10

{
    "content": "<:galaxy_alpha:792083061666873345> **GALAXY ALPHA** <:galaxy_alpha:792083061666873345>",
    "tts": false,
    "embed": {
        "title": "❓ Help and Support",
        "description": "Do you need help and nobody in the support channels can help you?\nThen use the got to <#787006398013505606> and use the command `!!ticketcreate [question]`!\n\nOtherwise use the support channels!",
        "type": "rich",
        "url": "https://discord.com/api/oauth2/authorize?client_id=761590139147124810&permissions=8&scope=bot",
        "footer": {
            "text": "Created By HydraNhani",
            "icon_url": "https://cdn.discordapp.com/avatars/761590139147124810/af4f3ecc03a56e0f9d63aa8c320f4a2a.webp"
        },
        "color": "3562376"
    }
}