POST https://discord.com/api/v8/channels/790654211414949899/messages
Content-Type: application/json
Authorization: Bot NzYxNTkwMTM5MTQ3MTI0ODEw.X3c0Fg.iCXl-m52KcN_XVxXjI4CC1F0P10

{
    "content": "<:galaxy_alpha:792083061666873345> **GALAXY ALPHA** <:galaxy_alpha:792083061666873345>",
    "tts": false,
    "embed": {
        "title": "<:info:786676407362781195> Help us",
        "description": "**Are you asking, why you should help us?**\nEvery kind of support will help us getting this bot more popular and every vote will give us more power to create much powerful commands, that can help you managing your server etc.\n\nSo there are many different ways to support us!\n\n**#1** [Vote for this bot on top.gg](https://top.gg/bot/761590139147124810/vote)\n**#2** [Vote for this bot on Discord Bot List](https://discordbotlist.com/bots/galaxy-alpha/upvote)\n**#3** [Vote for this server on top.gg](https://top.gg/servers/783440776285651024/vote)\n**#4** [Vote for this server on Discord Server List](https://discordbotlist.com/servers/galaxy-alpha/upvote)\n**#5** Use the command `!d bump` in <#790654261968371754> to bump us on [DISBOARD](https://disboard.org/de/server/783440776285651024)!",
        "type": "rich",
        "url": "https://discord.com/api/oauth2/authorize?client_id=761590139147124810&permissions=8&scope=bot",
        "footer": {
            "text": "Created By HydraNhani",
            "icon_url": "https://cdn.discordapp.com/avatars/761590139147124810/af4f3ecc03a56e0f9d63aa8c320f4a2a.webp"
        },
        "color": "3562376"
    }
}