import bodyParser from 'body-parser';
import cookies from 'cookies';
import express from 'express';
import { join } from "path";
import methodOverride from 'method-override';
import { updateUser, validateUser, updateGuilds } from '@modules/middleware';
import authRoutes from '@routes/auth-routes';
import dashboardRoutes from '@routes/dashboard-routes';
import rootRoutes from '@routes/root-routes';
export const subTitle = "A multipurpose bot";
const app = express();
app.set('views', join(__dirname, "Views"));
app.set('view engine', 'pug');
app.use(bodyParser.urlencoded({ extended: true }));
app.use(methodOverride('_method'));
app.use(cookies.express(["a", "b", "c"]));
app.use(express.static(join(__dirname, "Assets")));
app.locals.basedir = join(__dirname, "Assets");
app.use('/', updateUser, rootRoutes, authRoutes, validateUser, updateGuilds, dashboardRoutes);
app.all('*', (req, res) => res.render('Errors/404'));
const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`Server is live on port ${port}`));